version: '3'
services:
  cas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8443:8443"
     - "8000:8080"
    restart: always
    container_name: CAS-Template

  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=cas
      - POSTGRES_USER=casuser
      - POSTGRES_PASSWORD=caspassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    container_name: CAS-Database

volumes:
  db-data:


